// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {discovery} from '../models';
import {main} from '../models';
import {transfer} from '../models';

export function Accept(arg1:string):Promise<void>;

export function CopyText(arg1:string):Promise<void>;

export function CopyURL():Promise<void>;

export function DiscoverPeers():Promise<Array<discovery.Peer>>;

export function InstallTailscale():Promise<string>;

export function LocalAddr():Promise<string>;

export function MobileQR():Promise<string>;

export function MobileURL():Promise<string>;

export function OpenSaveDir():Promise<void>;

export function PickFiles():Promise<Array<string>>;

export function PickFolder():Promise<string>;

export function PickSaveDir():Promise<string>;

export function Reject(arg1:string):Promise<void>;

export function SaveDir():Promise<string>;

export function SendToPeer(arg1:string,arg2:number,arg3:Array<string>):Promise<void>;

export function SetGlobalLimit(arg1:number):Promise<void>;

export function SetTaskLimit(arg1:string,arg2:number):Promise<void>;

export function ShareAddFiles():Promise<main.ShareState>;

export function ShareAddFolder():Promise<main.ShareState>;

export function ShareRemove(arg1:string):Promise<main.ShareState>;

export function ShareState():Promise<main.ShareState>;

export function Tasks():Promise<Array<transfer.Task>>;
