// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Accept(arg1) {
  return window['go']['main']['App']['Accept'](arg1);
}

export function CopyText(arg1) {
  return window['go']['main']['App']['CopyText'](arg1);
}

export function CopyURL() {
  return window['go']['main']['App']['CopyURL']();
}

export function DiscoverPeers() {
  return window['go']['main']['App']['DiscoverPeers']();
}

export function InstallTailscale() {
  return window['go']['main']['App']['InstallTailscale']();
}

export function LocalAddr() {
  return window['go']['main']['App']['LocalAddr']();
}

export function MobileQR() {
  return window['go']['main']['App']['MobileQR']();
}

export function MobileURL() {
  return window['go']['main']['App']['MobileURL']();
}

export function OpenSaveDir() {
  return window['go']['main']['App']['OpenSaveDir']();
}

export function PickFiles() {
  return window['go']['main']['App']['PickFiles']();
}

export function PickFolder() {
  return window['go']['main']['App']['PickFolder']();
}

export function PickSaveDir() {
  return window['go']['main']['App']['PickSaveDir']();
}

export function Reject(arg1) {
  return window['go']['main']['App']['Reject'](arg1);
}

export function SaveDir() {
  return window['go']['main']['App']['SaveDir']();
}

export function SendToPeer(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendToPeer'](arg1, arg2, arg3);
}

export function SetGlobalLimit(arg1) {
  return window['go']['main']['App']['SetGlobalLimit'](arg1);
}

export function SetTaskLimit(arg1, arg2) {
  return window['go']['main']['App']['SetTaskLimit'](arg1, arg2);
}

export function ShareAddFiles() {
  return window['go']['main']['App']['ShareAddFiles']();
}

export function ShareAddFolder() {
  return window['go']['main']['App']['ShareAddFolder']();
}

export function ShareRemove(arg1) {
  return window['go']['main']['App']['ShareRemove'](arg1);
}

export function ShareState() {
  return window['go']['main']['App']['ShareState']();
}

export function Tasks() {
  return window['go']['main']['App']['Tasks']();
}
